### ISSUE TITLE
Create article on how VS22 users can build the project

### ISSUE THREAD

**Issue by Quit975** [Quit975/DuckyGame#20]
Currently the project is using VS19 toolset. In order to keep it that way, VS22 users need to dowload said toolset on their machines. Create an article on Wiki about how to do it, step by step

**Comment by Quit975** [comment]
I created a barebone skeleton for our wiki, here is the link for the article for this issue - you can write it [here](https://github.com/Quit975/DuckyGame/wiki/Downloading-Visual-Studio-2019-toolset-(v142)-for-Visual-Studio-2022-users)

**Comment by Quit975** [comment]
yay! there are screenshots! ❤️ 
there is a mistake on the last one though :p
![obraz](https://user-images.githubusercontent.com/24831298/169541315-914b55e0-559b-413a-9e08-1275259746ac.png)

**Comment by pyskaa0506** [comment]
Oh I see
Gonna fix that quickly
Also finally I have time to finish that page

**Comment by Quit975** [comment]
Very nicely written, awesome job! The last sentence
"Now non progressive people with who didn't want to upgrade can work with us 😄" should be the other way around :D "progressive people successfully downgraded their tools so that they can work with the ancients" xD
