### ISSUE TITLE
To Lua #41: Green enemies are zooming 

### ISSUE THREAD

**Issue by NNathaneel** [Quit975/DuckyGame#63]
Compared to the previous pack, which I downloaded (background update), the green enemies are much faster and my wood division skills aren't able to deal with this. The blue dot enemy tho is still travelling at the same pace as before, so I don't think it's the problem with the FPS as previously.

**Comment by Quit975** [comment]
👀 so on which package/version did you notice that issue?

**Comment by NNathaneel** [comment]
I used the Package #40. I used the workflow from Branch: lua_#41 without Debug configuration, cos my VS has run out of trial ver (I don't really think I had a trial one, but ok Microsoft).

**Comment by Quit975** [comment]
Closing as discussed on dc
