### ISSUE TITLE
Create central repository for loading files

### ISSUE THREAD

**Issue by pyskaa0506** [Quit975/DuckyGame#65]
Every class is loading music/textures by itself
There should be one place, that loads everything once

**Comment by Quit975** [comment]
What we require is a ResourceManager class of some sorts. It can be implemented as a Singleton or global variable (check out how ScriptManager is implemented). Loading all the assets at startup will be easier and most convenient for Ducky Game - no need to do streaming when our whole game takes up dozens of megabytes. For each resource type, we should have a HashMap probably, where its name is at the same time the key to that resource
