### ISSUE TITLE
Drawing of a duck

### ISSUE THREAD

**Issue by pyskaa0506** [Quit975/DuckyGame#75]
Create at least the prototype of the main character in the game

**Comment by pyskaa0506** [comment]
Update:
As i've started animating the duck, i've decided to go with side perspective

**Comment by pyskaa0506** [comment]
Here's the sketch of what im going for https://discord.com/channels/884485906755629086/885112955077816351/1003013174339051552

**Comment by pyskaa0506** [comment]
Progress is being made! Today i've finished the sketch of the animation.
https://cdn.discordapp.com/attachments/528201963075141662/1031623124015394887/2022-10-17_19-41-14.mp4 
(Shows the moment before i've added eyes and have corrected some things)

**Comment by Quit975** [comment]
Wow, that's a pretty cool animation :o

**Comment by pyskaa0506** [comment]
Okay i've finished the animation
https://cdn.discordapp.com/attachments/969342129979678720/1035626844474589254/2022-10-28_20-50-36.mp4
I will put the files in the Res directory, but i don't know if I should upload them as a gif or as a series of images.
