### ISSUE TITLE
File management - too many files to keep them in one folder

### ISSUE THREAD

**Issue by zielonoludek** [Quit975/DuckyGame#82]
We have almost 40 files in src folder. Maybe should we organize our files, so it'll look similar to VS Solution Explorer.

![image](https://user-images.githubusercontent.com/96289919/175836631-d7ce73f6-df8a-4654-9862-0e37a12ca382.png)

**Comment by Quit975** [comment]
I actually totally rearrange that in the scene graph branch to make it more organized :p

**Comment by Quit975** [comment]
Done in [aaca79c](https://github.com/Quit975/DuckyGame/commit/aaca79cb901d24d792469f5dec2968cbd693435f)
